// Code generated by mockery v2.53.4. DO NOT EDIT.

package easydb

import (
	context "context"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockDB) Begin(ctx context.Context) (Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockDB_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) Begin(ctx interface{}) *MockDB_Begin_Call {
	return &MockDB_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockDB_Begin_Call) Run(run func(ctx context.Context)) *MockDB_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_Begin_Call) Return(_a0 Tx, _a1 error) *MockDB_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Begin_Call) RunAndReturn(run func(context.Context) (Tx, error)) *MockDB_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockDB) Close() {
	_m.Called()
}

// MockDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDB_Expecter) Close() *MockDB_Close_Call {
	return &MockDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDB_Close_Call) Run(run func()) *MockDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Close_Call) Return() *MockDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDB_Close_Call) RunAndReturn(run func()) *MockDB_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function with given fields: ctx, query, args
func (_m *MockDB) Exec(ctx context.Context, query string, args ...interface{}) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDB_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *MockDB_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *MockDB_Exec_Call {
	return &MockDB_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDB_Exec_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *MockDB_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *MockDB_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Exec_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)) *MockDB_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, dest, query, args
func (_m *MockDB) Get(ctx context.Context, dest interface{}, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDB_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockDB_Expecter) Get(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *MockDB_Get_Call {
	return &MockDB_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *MockDB_Get_Call) Run(run func(ctx context.Context, dest interface{}, query string, args ...interface{})) *MockDB_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_Get_Call) Return(_a0 error) *MockDB_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Get_Call) RunAndReturn(run func(context.Context, interface{}, string, ...interface{}) error) *MockDB_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuerier provides a mock function with no fields
func (_m *MockDB) GetQuerier() pgxquerier {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQuerier")
	}

	var r0 pgxquerier
	if rf, ok := ret.Get(0).(func() pgxquerier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgxquerier)
		}
	}

	return r0
}

// MockDB_GetQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuerier'
type MockDB_GetQuerier_Call struct {
	*mock.Call
}

// GetQuerier is a helper method to define mock.On call
func (_e *MockDB_Expecter) GetQuerier() *MockDB_GetQuerier_Call {
	return &MockDB_GetQuerier_Call{Call: _e.mock.On("GetQuerier")}
}

func (_c *MockDB_GetQuerier_Call) Run(run func()) *MockDB_GetQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_GetQuerier_Call) Return(_a0 pgxquerier) *MockDB_GetQuerier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_GetQuerier_Call) RunAndReturn(run func() pgxquerier) *MockDB_GetQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// NamedExec provides a mock function with given fields: ctx, query, arg
func (_m *MockDB) NamedExec(ctx context.Context, query string, arg interface{}) (pgconn.CommandTag, error) {
	ret := _m.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedExec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, query, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, query, arg)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_NamedExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedExec'
type MockDB_NamedExec_Call struct {
	*mock.Call
}

// NamedExec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg interface{}
func (_e *MockDB_Expecter) NamedExec(ctx interface{}, query interface{}, arg interface{}) *MockDB_NamedExec_Call {
	return &MockDB_NamedExec_Call{Call: _e.mock.On("NamedExec", ctx, query, arg)}
}

func (_c *MockDB_NamedExec_Call) Run(run func(ctx context.Context, query string, arg interface{})) *MockDB_NamedExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockDB_NamedExec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *MockDB_NamedExec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_NamedExec_Call) RunAndReturn(run func(context.Context, string, interface{}) (pgconn.CommandTag, error)) *MockDB_NamedExec_Call {
	_c.Call.Return(run)
	return _c
}

// NamedGet provides a mock function with given fields: ctx, dest, query, arg
func (_m *MockDB) NamedGet(ctx context.Context, dest interface{}, query string, arg interface{}) error {
	ret := _m.Called(ctx, dest, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedGet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, interface{}) error); ok {
		r0 = rf(ctx, dest, query, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_NamedGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedGet'
type MockDB_NamedGet_Call struct {
	*mock.Call
}

// NamedGet is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - arg interface{}
func (_e *MockDB_Expecter) NamedGet(ctx interface{}, dest interface{}, query interface{}, arg interface{}) *MockDB_NamedGet_Call {
	return &MockDB_NamedGet_Call{Call: _e.mock.On("NamedGet", ctx, dest, query, arg)}
}

func (_c *MockDB_NamedGet_Call) Run(run func(ctx context.Context, dest interface{}, query string, arg interface{})) *MockDB_NamedGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *MockDB_NamedGet_Call) Return(_a0 error) *MockDB_NamedGet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_NamedGet_Call) RunAndReturn(run func(context.Context, interface{}, string, interface{}) error) *MockDB_NamedGet_Call {
	_c.Call.Return(run)
	return _c
}

// NamedSelect provides a mock function with given fields: ctx, dest, query, arg
func (_m *MockDB) NamedSelect(ctx context.Context, dest interface{}, query string, arg interface{}) error {
	ret := _m.Called(ctx, dest, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedSelect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, interface{}) error); ok {
		r0 = rf(ctx, dest, query, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_NamedSelect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedSelect'
type MockDB_NamedSelect_Call struct {
	*mock.Call
}

// NamedSelect is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - arg interface{}
func (_e *MockDB_Expecter) NamedSelect(ctx interface{}, dest interface{}, query interface{}, arg interface{}) *MockDB_NamedSelect_Call {
	return &MockDB_NamedSelect_Call{Call: _e.mock.On("NamedSelect", ctx, dest, query, arg)}
}

func (_c *MockDB_NamedSelect_Call) Run(run func(ctx context.Context, dest interface{}, query string, arg interface{})) *MockDB_NamedSelect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *MockDB_NamedSelect_Call) Return(_a0 error) *MockDB_NamedSelect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_NamedSelect_Call) RunAndReturn(run func(context.Context, interface{}, string, interface{}) error) *MockDB_NamedSelect_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function with given fields: ctx, dest, query, args
func (_m *MockDB) Select(ctx context.Context, dest interface{}, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockDB_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockDB_Expecter) Select(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *MockDB_Select_Call {
	return &MockDB_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *MockDB_Select_Call) Run(run func(ctx context.Context, dest interface{}, query string, args ...interface{})) *MockDB_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_Select_Call) Return(_a0 error) *MockDB_Select_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Select_Call) RunAndReturn(run func(context.Context, interface{}, string, ...interface{}) error) *MockDB_Select_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *MockDB) WithTx(ctx context.Context, fn func(Querier) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(Querier) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockDB_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(Querier) error
func (_e *MockDB_Expecter) WithTx(ctx interface{}, fn interface{}) *MockDB_WithTx_Call {
	return &MockDB_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockDB_WithTx_Call) Run(run func(ctx context.Context, fn func(Querier) error)) *MockDB_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(Querier) error))
	})
	return _c
}

func (_c *MockDB_WithTx_Call) Return(_a0 error) *MockDB_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_WithTx_Call) RunAndReturn(run func(context.Context, func(Querier) error) error) *MockDB_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
