// Code generated by mockery v2.53.4. DO NOT EDIT.

package easydb

import (
	context "context"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, query, args
func (_m *MockQuerier) Exec(ctx context.Context, query string, args ...interface{}) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockQuerier_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *MockQuerier_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *MockQuerier_Exec_Call {
	return &MockQuerier_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockQuerier_Exec_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *MockQuerier_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockQuerier_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *MockQuerier_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_Exec_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)) *MockQuerier_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, dest, query, args
func (_m *MockQuerier) Get(ctx context.Context, dest interface{}, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockQuerier_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockQuerier_Expecter) Get(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *MockQuerier_Get_Call {
	return &MockQuerier_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *MockQuerier_Get_Call) Run(run func(ctx context.Context, dest interface{}, query string, args ...interface{})) *MockQuerier_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockQuerier_Get_Call) Return(_a0 error) *MockQuerier_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_Get_Call) RunAndReturn(run func(context.Context, interface{}, string, ...interface{}) error) *MockQuerier_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuerier provides a mock function with no fields
func (_m *MockQuerier) GetQuerier() pgxquerier {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQuerier")
	}

	var r0 pgxquerier
	if rf, ok := ret.Get(0).(func() pgxquerier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgxquerier)
		}
	}

	return r0
}

// MockQuerier_GetQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuerier'
type MockQuerier_GetQuerier_Call struct {
	*mock.Call
}

// GetQuerier is a helper method to define mock.On call
func (_e *MockQuerier_Expecter) GetQuerier() *MockQuerier_GetQuerier_Call {
	return &MockQuerier_GetQuerier_Call{Call: _e.mock.On("GetQuerier")}
}

func (_c *MockQuerier_GetQuerier_Call) Run(run func()) *MockQuerier_GetQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuerier_GetQuerier_Call) Return(_a0 pgxquerier) *MockQuerier_GetQuerier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_GetQuerier_Call) RunAndReturn(run func() pgxquerier) *MockQuerier_GetQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// NamedExec provides a mock function with given fields: ctx, query, arg
func (_m *MockQuerier) NamedExec(ctx context.Context, query string, arg interface{}) (pgconn.CommandTag, error) {
	ret := _m.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedExec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, query, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, query, arg)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_NamedExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedExec'
type MockQuerier_NamedExec_Call struct {
	*mock.Call
}

// NamedExec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg interface{}
func (_e *MockQuerier_Expecter) NamedExec(ctx interface{}, query interface{}, arg interface{}) *MockQuerier_NamedExec_Call {
	return &MockQuerier_NamedExec_Call{Call: _e.mock.On("NamedExec", ctx, query, arg)}
}

func (_c *MockQuerier_NamedExec_Call) Run(run func(ctx context.Context, query string, arg interface{})) *MockQuerier_NamedExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockQuerier_NamedExec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *MockQuerier_NamedExec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_NamedExec_Call) RunAndReturn(run func(context.Context, string, interface{}) (pgconn.CommandTag, error)) *MockQuerier_NamedExec_Call {
	_c.Call.Return(run)
	return _c
}

// NamedGet provides a mock function with given fields: ctx, dest, query, arg
func (_m *MockQuerier) NamedGet(ctx context.Context, dest interface{}, query string, arg interface{}) error {
	ret := _m.Called(ctx, dest, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedGet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, interface{}) error); ok {
		r0 = rf(ctx, dest, query, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_NamedGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedGet'
type MockQuerier_NamedGet_Call struct {
	*mock.Call
}

// NamedGet is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - arg interface{}
func (_e *MockQuerier_Expecter) NamedGet(ctx interface{}, dest interface{}, query interface{}, arg interface{}) *MockQuerier_NamedGet_Call {
	return &MockQuerier_NamedGet_Call{Call: _e.mock.On("NamedGet", ctx, dest, query, arg)}
}

func (_c *MockQuerier_NamedGet_Call) Run(run func(ctx context.Context, dest interface{}, query string, arg interface{})) *MockQuerier_NamedGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *MockQuerier_NamedGet_Call) Return(_a0 error) *MockQuerier_NamedGet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_NamedGet_Call) RunAndReturn(run func(context.Context, interface{}, string, interface{}) error) *MockQuerier_NamedGet_Call {
	_c.Call.Return(run)
	return _c
}

// NamedSelect provides a mock function with given fields: ctx, dest, query, arg
func (_m *MockQuerier) NamedSelect(ctx context.Context, dest interface{}, query string, arg interface{}) error {
	ret := _m.Called(ctx, dest, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedSelect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, interface{}) error); ok {
		r0 = rf(ctx, dest, query, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_NamedSelect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedSelect'
type MockQuerier_NamedSelect_Call struct {
	*mock.Call
}

// NamedSelect is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - arg interface{}
func (_e *MockQuerier_Expecter) NamedSelect(ctx interface{}, dest interface{}, query interface{}, arg interface{}) *MockQuerier_NamedSelect_Call {
	return &MockQuerier_NamedSelect_Call{Call: _e.mock.On("NamedSelect", ctx, dest, query, arg)}
}

func (_c *MockQuerier_NamedSelect_Call) Run(run func(ctx context.Context, dest interface{}, query string, arg interface{})) *MockQuerier_NamedSelect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *MockQuerier_NamedSelect_Call) Return(_a0 error) *MockQuerier_NamedSelect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_NamedSelect_Call) RunAndReturn(run func(context.Context, interface{}, string, interface{}) error) *MockQuerier_NamedSelect_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockQuerier) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockQuerier_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) Ping(ctx interface{}) *MockQuerier_Ping_Call {
	return &MockQuerier_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockQuerier_Ping_Call) Run(run func(ctx context.Context)) *MockQuerier_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_Ping_Call) Return(_a0 error) *MockQuerier_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_Ping_Call) RunAndReturn(run func(context.Context) error) *MockQuerier_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function with given fields: ctx, dest, query, args
func (_m *MockQuerier) Select(ctx context.Context, dest interface{}, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockQuerier_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockQuerier_Expecter) Select(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *MockQuerier_Select_Call {
	return &MockQuerier_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *MockQuerier_Select_Call) Run(run func(ctx context.Context, dest interface{}, query string, args ...interface{})) *MockQuerier_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockQuerier_Select_Call) Return(_a0 error) *MockQuerier_Select_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_Select_Call) RunAndReturn(run func(context.Context, interface{}, string, ...interface{}) error) *MockQuerier_Select_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
